services:

  mysql:
    image: mysql:8.0
    container_name: hireshield-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: hireshield
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - hireshield_mysql_data:/var/lib/mysql


  backend:
    build:
      context: ./backend

    container_name: hireshield-backend
    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hireshield?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root

    ports:
      - "8080:8080"


  frontend:
    build:
      context: ./frontend

    container_name: hireshield-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5500:80"


volumes:
  hireshield_mysql_data: